interfaces/index.ts
pages/api/projects.ts

feat: added projects route

---

components/Projects/Project.tsx
components/Search/Search.tsx
pages/projects.tsx

- fixed language chips borders and background colors
- added border to search bar
- added border to project card

fix: UI issues

---

components/Navbar/Navbar.tsx

✅ Fixed inconsistent size of navbar icons ( #97 ) 
fixes #97

fixed inconsistent size of navbar icons

---

components/Navbar/Navbar.tsx
components/Tooltip/Tooltip.tsx

fixes #104 
* added tooltip for navbar icons 
* added link to logo

feat: added tooltip to nav icons

---

package-lock.json
package.json
pages/index.tsx

- Updated from `lottie-web-react`  to `lottie-react` library

updated lottie library

---

components/ContributorList/ContributorList.interface.ts
components/ContributorList/ContributorList.tsx
components/Projects/Project.interface.ts
components/Projects/Project.tsx
components/Projects/index.ts
components/Tooltip/index.tsx
pages/about.tsx

fix: about page issue and code improvement

---

README.md
components/Projects/Project.tsx
package-lock.json
package.json
pages/projects.tsx

fixes #115 
* added action button - for adding project (also can be added more buttons to it)
* responsive issue fix
* readme color fix

115 feature add add project button to the app

---

interfaces/schema/index.ts
interfaces/schema/postSchema.ts
interfaces/schema/userSchema.ts
lib/apiHandler.ts
lib/bodyValidator.ts
lib/http.response.ts
package-lock.json
package.json
pages/api/project/[postId].ts
pages/api/project/index.ts
pages/api/user/[userId].ts
pages/api/user/index.ts
tsconfig.json

- Validated create user data
- Validated create project data
- Added Path Aliases for (`@/schema/`, `@/lib/`, `@/components/`)
**Validate Create user data**
**Validate Create post data**

127 bug validating a nextjs api endpoint

---

components/AuthModal/AuthModal.tsx
interfaces/schema/postSchema.ts
pages/api/project/index.ts
pages/api/user/index.ts
prisma/schema.prisma

- Create a user when login 1st time (if the user already exists DB won't update)
- If something goes wrong while creating a user, it will automatically logout and ask to login again.
- Code refactor ( make `Google` and `GitHub` login handler to the same function )
- Added project cover image for db
- improvements

Create user when login

---

components/AuthModal/AuthModal.tsx
pages/index.tsx

Improved the login UI

---

components/AuthModal/AuthModal.tsx
lib/firebase.ts
pages/index.tsx
pages/projects.tsx

fixed ui issues in login modal / auth modal
* padding and alignment stuff

fix: auth modal ui

---

components/Projects/Project.tsx
components/Search/Search.tsx
pages/projects.tsx
styles/globals.css

Closes #154
Fixed the mentioned issues

resolved projects cards issues

---

components/Layouts/SharedLayout.tsx
components/ThemeToggler/ThemeToggler.tsx
components/Topbar/Sidebar.tsx
components/Topbar/Topbar.tsx
pages/about.tsx
pages/index.tsx
pages/projects.tsx

Closes #162
added a sharedLayout to the project

fix: added sharedLayout

---

package.json

fix: remove floating button package

---

components/AuthModal/AuthModal.tsx
components/Avatar/Avatar.tsx
components/Layouts/index.ts
components/Topbar/DesktopRoutes.tsx
components/Topbar/Sidebar.tsx
components/index.ts
interfaces/schema/postSchema.ts
package-lock.json
package.json
pages/about.tsx
pages/api/auth/[...nextauth].ts
pages/api/project/index.ts
pages/index.tsx
pages/projects/[projectId].tsx
pages/projects/index.tsx
pages/projects/submit.tsx

closes #175 
1. Project Page structure improved
2. Removed toast message - due to some issues with that
3. re-written add project page
4. added react-hook-form
5. added validation
6. integrated with add project api

feat: submit project integration with backend

---

components/Projects/Project.tsx
pages/api/project/index.ts
pages/projects/submit.tsx

- Pagination API 
- Project limit (default 10)

Paginated API 

---

components/Topbar/DesktopRoutes.tsx
components/Topbar/Sidebar.tsx
components/Topbar/SocialLinks.tsx
components/Topbar/Topbar.tsx
components/Topbar/data.ts

Closes #184 
Creating a new social media link rendering component

fix social media links

---

components/ThemeToggler/ThemeToggler.tsx
components/Topbar/SocialLinks.tsx

Closes #199 
- Adding hover effect on toggle theme and social links on topbar

closes#199 add hover effect on social links and theme toggle

---

components/Topbar/data.ts
pages/blog/index.tsx

Closes #213
added a coming soon blog section

added blog section

---

components/Projects/Project.tsx

Text overflow on project component title.
Added truncate class on title header.

Fixed line break in project component

---

components/Layouts/SharedLayout.tsx

This error shows of a lot when in Dark Reader on.

Add or update the UI and style files: Footer Border adjustment.

---

components/LandingPage/About.tsx
components/LandingPage/Benefit.tsx
components/LandingPage/Guide.tsx
components/LandingPage/Hero.tsx

Removed absolute values of classes.
This helps to tailwind export fewer classes.

Changed tailwind absolute values

---

pages/api/user/project.ts

- Get all the projects created by the user
PATH
`/api/user/project`
> User needs to log in to get data

Get user projects

---

pages/user/profile.tsx

fix: blank profile

---

pages/projects/[projectId].tsx

Fix for tags not displaying correct value in project details issue

---

package-lock.json
package.json

Update axios version

---

components/Topbar/data.ts

Closes #248
Added Twitter link in the topbar and sidebar

added twitter logo in topbar

---

components/Projects/Project.tsx
components/Projects/ProjectSkeleton.tsx

Used to have a flicker type of issue in projects when it loads. to fix that added a smooth entrance
* added animation to projects and a shadow
please share your views

improve: projects card animation

---

components/FloatingButtonMenu/FloatingButtonMenu.interface.ts
components/FloatingButtonMenu/FloatingMenu.tsx
components/LandingPage/Hero.tsx
components/Projects/Project.tsx
components/Projects/Tags.tsx
components/SubmitPageForm/SubmitPageForm.tsx
pages/projects/[projectId].tsx
pages/projects/index.tsx

* changed colors according to the theme

fix: color adjusted to match theme

---

components/Profile/Project/Project.tsx
components/Projects/Project.tsx
components/Projects/ProjectsList.tsx
pages/user/profile.tsx

Closes #241 
- I used the right semantics.
I decided to use `ul` for the general container since there will always be at least one project.

Improve projects page accessibility

---

components/Button/Button.tsx
components/Button/index.ts
components/LandingPage/Hero.tsx
components/Projects/Project.tsx
components/SubmitPageForm/SubmitPageForm.tsx

Extracting essential button styles and making it reusable

Extract buttons to component and making it reusable

---

components/Layouts/SharedLayout.tsx
components/Projects/Project.tsx
pages/api/project/[postId].ts
pages/projects/[projectId].tsx

closes #261 
removed auth guard in get project details from FE and BE

feat: removed auth guard in get project details

---

components/Button/Button.tsx

closes #273 
[feature]: Add Hover effect to buttons
Added Hover effect to buttons

hover effect added on buttons

---

components/LandingPage/data.ts
components/Topbar/LoginButton.tsx
components/Topbar/Sidebar.tsx
components/Topbar/Topbar.tsx

Closes #279 
1. created component LoginButton
2. added this component into topbar.tsx
3. added a login button into sidebar
Let me know for any kind of changes if needed 
**Desktop**
**Other than desktop**

feat: Adding login button in topbar

---

components/Button/Button.tsx
components/LandingPage/About.tsx
components/LandingPage/Benefit.tsx
components/LandingPage/Guide.tsx
components/LandingPage/Hero.tsx
components/Stats/Stats.tsx
components/ThemeToggler/ThemeToggler.tsx
components/Topbar/DesktopRoutes.tsx
components/Topbar/LoginButton.tsx
components/Topbar/SocialLinks.tsx
components/Topbar/Topbar.tsx
pages/projects/[projectId].tsx

refactor: ui changes

---

components/Projects/ProjectsList.tsx
components/Topbar/Topbar.tsx
pages/projects/index.tsx

chore: removed searchbar temporarily

---

components/Avatar/Avatar.tsx
components/Stats/Stats.tsx
components/Tags/Tags.tsx
pages/projects/[projectId].tsx
pages/user/profile.tsx

minor ui improvements

---

components/BackToTopButton/BackToTop.tsx
components/LandingPage/Hero.tsx
components/Layouts/SharedLayout.tsx
pages/projects/index.tsx

fix issues

---

components/SubmitPageForm/SubmitPageForm.tsx
pages/api/project/index.ts
prisma/seed.ts

removed content(temporarily, it will be replaced by markdown)

---

README.md

Closes #308 
Changes old production URL to the current one, as requested in issue #308 
Old:
New:

Update readme.md to current production link

---

components/Stats/Stats.tsx
pages/projects/[projectId].tsx

fix: added optional chaining

---

components/Layouts/SharedLayout.tsx
components/Topbar/Sidebar.tsx
pages/blog/index.tsx
pages/index.tsx
pages/projects/index.tsx
pages/user/profile.tsx

feat: ui improvements

---

components/Layouts/SharedLayout.tsx
components/Markdown/privacy-policy.md
components/Topbar/Sidebar.tsx
pages/privacy-policy/index.tsx

feat: improve privacy policy page

---

components/Stats/Stats.tsx
pages/projects/[projectId].tsx

project details page revamp

---

components/AuthModal/AuthModal.tsx
components/Avatar/SidebarAvatar.tsx
components/Form/Input/Input.tsx
components/Form/RichTextEditor/RichTextEditor.tsx
components/LandingPage/About.tsx
components/LandingPage/Guide.tsx
components/LandingPage/Hero.tsx
components/LandingPage/JoinUs.tsx
components/LandingPage/Thanks.tsx
components/Profile/Project/Project.tsx
components/Projects/Project.tsx
components/Stats/Stats.tsx
components/SubmitPageForm/SubmitPageForm.tsx
components/Typography/Typography.interface.ts
pages/projects/[projectId].tsx
pages/user/profile.tsx

307 chore replace text elements with existing typography component

---

components/Layouts/SharedLayout.tsx
components/Markdown/privacy-policy.md
components/SubmitPageForm/SubmitPageForm.tsx
components/Tags/Tag.tsx
pages/privacy-policy/index.tsx
pages/projects/submit.tsx

submit page improvements

---

components/ErrorFallback/ErrorFallback.tsx
components/ErrorFallback/index.ts
package.json
pages/_app.tsx
pages/index.tsx
yarn.lock

Closes #311 
- Installed `react-error-boundary`
- Added and styled  an `ErrorFallback` component
- Wrapped `_app.tsx` with `ErrorBoundary`

added error boundary, fix #311

---

components/BackToTopButton/BackToTop.tsx
components/LandingPage/Hero.tsx
components/ProductHunt/ProductHunt.tsx
components/Projects/Project.tsx
components/Topbar/Logo.tsx
components/Topbar/Sidebar.tsx
components/Topbar/Topbar.tsx
pages/_document.tsx

chore: improve ux

---

components/LandingPage/Guide.tsx
components/LandingPage/Hero.tsx
components/People/People.interface.ts
components/People/People.tsx
components/People/Person.tsx
components/People/index.ts
components/Topbar/DesktopRoutes.tsx
components/Topbar/data.ts
pages/api/user/all.ts
pages/user/all.tsx

feat: showing userlist

---

components/People/People.tsx
components/People/Person.tsx

Hi, I changed the flexbox to grid. I tried in development mode and it looked well.
Should closes #339 
Classes of div in `People` component.
Classes of motion.div in `Person` component.

Fixed alignment of Mates profile cards

---

components/Projects/ProjectsList.tsx

I replaced the index key with project id in the `ProjectsList` component.
Closes #341

fix: replaced index key with project id

---

components/People/Person.tsx

Should closes #345 
I added trim function to the `Person` component.

Added trim function to delete unnecessary whitespaces.

---

components/Form/Textarea/Textarea.interface.ts
components/Form/Textarea/Textarea.tsx
components/Form/Textarea/index.ts
components/SubmitPageForm/SubmitPageForm.tsx

Hi! I added a reusable textarea component to `SubmitPageForm` component.
Closes #347

feat: Added textarea to the description field

---

pages/user/all.tsx

[FEATURE] add back to top button in Mates page#349

---

components/ErrorFallback/ErrorFallback.tsx

Hi! I fixed the display of long error message in the `ErrorFallback` component. The component also looks better in the mobile view.
Closes #351 
- I fixed the CSS classes of the `ErrorFallback` component.

fix: Fixed the display of error

---

components/Layouts/SharedLayout.tsx
components/Topbar/Sidebar.tsx
components/Topbar/Topbar.tsx
pages/404.tsx
public/robots.txt

- improved accessibility of navbar hamburger
- improved social links accessibility
- added robots.txt file to restrict crawlers from indexing certain pages
Closes: #324

Enhance site SEO and accessibility

---

components/ContributorList/ContributorList.tsx
components/Form/MultiSelectInput/MultiSelectInput.tsx
components/LandingPage/Benefit.tsx
components/LandingPage/Guide.tsx
components/LandingPage/Hero.tsx
components/LandingPage/Thanks.tsx
components/Projects/Project.tsx
components/Stats/Stats.tsx
components/Tags/Tag.tsx
components/Tags/Tags.tsx
pages/projects/[projectId].tsx
pages/projects/index.tsx

Partially: #363 
Improve site's accessibility

363 site accessibility

---

app/hooks.ts
interfaces/schema/postSchema.ts
store/slices/sliceModal.ts

chore: removed extra whitespaces and redundant lines

---

components/Layouts/Sidebar/data.ts
pages/mates/index.tsx
pages/posts/index.tsx

feat: added placeholder pages for future pages

---

components/Layouts/Sidebar/Sidebar.tsx

fix: sidebar issue

---

components/LandingPage/HeroComponent/HeroComponent.tsx

Closes #384
- Fixed the button div issue by adding the 'items-center' property to the parent div

fix: button div issue

---

components/Layouts/SharedLayout/SharedLayout.tsx
components/Layouts/Sidebar/Sidebar.tsx
components/ProjectsPage/Project/Project.tsx

Closes #383 
Fix sidebar issue caused by project component, make sidebar taking 1 column of SharedLayout component

improve the existing layout of the app

---

components/AuthModal/AuthModal.tsx

Closes #388 
In the future, we could extract the usePreviousRoute hook from its current location to _app.tsx and share the previous route data with the Context API or a different approach, in case other components need it.
[Screencast from 14-05-23 17:28:08.webm](https://github.com/rohitdasu/projectmate/assets/74047866/826b3577-d153-44f8-b091-e976bcaf513e)

Resolve auth modal bug

---

components/LandingPage/Footer/Footer.tsx
components/Layouts/Sidebar/SessionCard.tsx
components/Layouts/Sidebar/SessionLessCard.tsx
components/Layouts/Sidebar/Sidebar.tsx
pages/mates/index.tsx

Close #386 
Changed to color of text from `text-gray-500` and `hover:text-gray-400` to  `text-gray-400` and `hover:text-gray-300`
Fixes the WCAG contrast issue

fix: WCAG color contrast issue in footer

---

components/ProjectsPage/Project/Project.interface.ts
components/ProjectsPage/Project/Project.tsx
components/ProjectsPage/ProjectsList/ProjectsList.tsx
components/ShareModal/ShareModal.interface.ts
components/ShareModal/ShareModal.tsx
components/ShareModal/index.ts
package.json
yarn.lock

Closes #382
Added sharing buttons for
- Email
- Facebook
- Twitter
- Whatsapp
- Linkedin
Also added manual copying option for repository url

382 feature sharing feature should be enable

---

components/ProjectsPage/Project/Project.tsx
components/ProjectsPage/ProjectsList/ProjectsList.tsx
next.config.js
package.json
pages/api/project/index.ts
yarn.lock

Closes #391 
Added next bundle analyzer for future bundle size optimalization

[Improvement] Reduce projects page load time

---

components/ProjectsPage/Project/Project.tsx

Closes #402 
- Included reference in the URL of repository when clicked on contribute.

Included ref in contribute redirection query

---

components/LandingPage/Footer/Footer.interface.ts
components/LandingPage/Footer/Footer.tsx
components/LandingPage/Footer/data.tsx
components/Layouts/Sidebar/Sidebar.tsx
components/Layouts/Sidebar/data.tsx

Closes #405 
Changes in directory:
1. /components/LandingPage/Footer
To only import the necessary icons.
This PR  right now only consists of refactoring the imports for the footer in the landing page, later on, a commit can be added to this PR to refactor the sidebar component as well.

chore: remove unnecessary icons import (#405)

---

components/Layouts/Sidebar/SessionLessCard.tsx
components/Layouts/Sidebar/Sidebar.tsx
components/Layouts/Sidebar/data.tsx

Closes Issue https://github.com/rohitdasu/projectmate/issues/416
closes #416 
fixed styling of svg icons to align them with text 
Also in SideBar outputting span tag differently according to active state

fixed sidebar

---

components/views/ProjectsPage/Project/Project.tsx

Closes #425
- Wraps the title of the project with the project repository link.
- Added on hover mouse pointer for interactivity.

feat:wrap project name in project link

---

pages/index.tsx

tag: #433 change the page title
closes #433

Change the Page title

---

components/Modals/AddProjectModal/schema.ts
components/views/ProfilePage/schema.ts
schema/postSchema.ts
schema/userDetailsSchema.ts

Closes #432
Added validation in postSchema. , userDetailsSchema, profilepage schema, Addprojectmodal schema

#432 Added zod both in Frontend and backend with Validation
